[server]
headless = true
address = "localhost"
port = 8501

enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"